### ISSUE TITLE
Heavy prod .js file

### ISSUE THREAD

**Issue by mapi33** [gopangolin/wp-reactivate#11]
My app folder weights 110Kb, however the final shortcode.js file is almost 700Kb.
I have tried source-map-explorer in order to analyze the prod files. But the analysis doesn't give anything. I suspect for the following reason described in the package page:

"For source-map-explorer to be useful, you need to generate a source map which maps positions in your minified file all the way back to the files from which they came.
If you use browserify, you can generate a JavaScript file with an inline source map using the --debug flag:
browserify -r .:foo --debug -o foo.bundle.js
source-map-explorer foo.bundle.js"

How can I lower the weight of my prod .js file?
Or any chance I can eject the config in order to add the --debug flag?

**Comment by dnusca** [comment]
Hey mapi33,

This is due to the setup of babel-preset-env including all polyfills.I don't have a fix for you as I plan to retire this version of the boilerplate, but you can read the Babel docs on it (particularly around useBuiltIns).

There is no config to eject like CRA, you can edit the babelrc and webpack config directly!
